let myAge = 24
let yearAge = 1998
let birthNumber = 13
let numberMyBrother = 4
let numberMySister = 0
let numberPeopleFamily = 6
let fare = 50
let thisYear = 2023
let dollarRate = 81
let euroRate = 92
let bitcoinRate = 3400000
let test = thisYear - yearAge
let test2 = thisYear - myAge
let test3 = numberMyBrother + numberMySister
let test4 = euroRate * 1000
let test5 = dollarRate * 2.5
let test6 = fare / dollarRate
let test7 = numberPeopleFamily - numberMyBrother -numberMySister
let test8 = myAge / 0
let test9 =  myAge -35 